version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - apt-get install -y unzip

  build:
    commands:
      - echo Build started on `date`
      - zip hello.zip ./index.html ./aws.gif ./1.png ./back.jpg
   
artifacts:
  type: 
  files:
    - index.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
